package ninefoo.model.object;

import ninefoo.config.Config;
import ninefoo.helper.DateHelper;

import java.util.Date;

/**
 * This class represents a member entity in the database.
 * Created on 30-May-2015.
 * @author Farzad MajidFayyaz
 */
public class Member {
    private int memberId;
    private String firstName;
    private String lastName;
    private String username;
    private String password;
    private Date registerDate;

    /**
     * This constructor is only used when we want to convert db entities to Java classes
     * @param memberId ID of the member
     * @param firstName First name
     * @param lastName last name
     * @param username Username
     * @param password Password
     * @param registerDate Date of registration
     */
    public Member(int memberId, String firstName, String lastName,
           String username, String password, Date registerDate) {

        this.memberId = memberId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.username = username;
        this.password = password;
        this.registerDate = (Date)registerDate.clone();
    }

    /**
     * This constructor should be used when creating a new member in Java code because
     *      the ID is generated by the DB when the member is inserted into the table.
     * @param firstName First name
     * @param lastName Last name
     * @param username Username
     * @param password Password
     */
    public Member(String firstName, String lastName, String username,
                  String password) {

        this.firstName = firstName;
        this.lastName = lastName;
        this.username = username;
        this.password = password;
    }

    public int getMemberId() {
        return memberId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Date getRegisterDate() {
        return registerDate;
    }

    public String toString() {
        return String.format("Member [ID: %d, FirstName: '%s', LastName: '%s', " +
                "Username: '%s', Password: '%s', Register: '%s']", memberId,
                firstName, lastName, username, password, registerDate);
    }

    public boolean equals(Object other) {
        if (other == null)
            return false;

        Member otherMember = (Member) other;
        return (otherMember.getMemberId() == this.getMemberId() ||
                otherMember.getUsername().equals(this.getUsername()));
    }
}
